var child = [
  { 'dupe': false, 'type': 4, 'name': 'index', 'dir': 'c0', 'linked': 2, 'url': 'http://127.0.0.1:3000/index/', 'fetched': true, 'code': 200, 'len': 117, 'decl_mime': 'text/html', 'sniff_mime': 'text/html', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfffbffff },
  { 'dupe': false, 'type': 4, 'name': 'login', 'dir': 'c1', 'linked': 5, 'url': 'http://127.0.0.1:3000/login/', 'fetched': true, 'code': 200, 'len': 207, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 3, 'issue_cnt': [ 4, 1, 0, 0, 0 ], 'sig': 0xa4d4e2f9 },
  { 'dupe': false, 'type': 4, 'name': 'newPass', 'dir': 'c2', 'linked': 5, 'url': 'http://127.0.0.1:3000/newPass/', 'fetched': true, 'code': 200, 'len': 183, 'decl_mime': 'text/html', 'sniff_mime': 'text/html', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 3, 'issue_cnt': [ 3, 0, 1, 0, 0 ], 'sig': 0xfe0309b6 },
  { 'dupe': false, 'type': 4, 'name': 'register', 'dir': 'c3', 'linked': 5, 'url': 'http://127.0.0.1:3000/register/', 'fetched': true, 'code': 200, 'len': 311, 'decl_mime': 'text/html', 'sniff_mime': 'text/html', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 5, 'issue_cnt': [ 7, 3, 0, 0, 0 ], 'sig': 0xf9b541df },
  { 'dupe': false, 'type': 4, 'name': 'user', 'dir': 'c4', 'linked': 5, 'url': 'http://127.0.0.1:3000/user/', 'fetched': true, 'code': 302, 'len': 28, 'decl_mime': 'text/plain', 'sniff_mime': 'text/plain', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 16, 'issue_cnt': [ 12, 0, 3, 0, 0 ], 'sig': 0x90ac0374 },
  { 'dupe': false, 'type': 4, 'name': 'user', 'dir': 'c5', 'linked': 2, 'url': 'http://127.0.0.1:3000/user/', 'fetched': true, 'code': 302, 'len': 28, 'decl_mime': 'text/plain', 'sniff_mime': 'text/plain', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 1, 0, 0, 0 ], 'sig': 0xd6b3b7e0 },
  { 'dupe': false, 'type': 4, 'name': 'user', 'dir': 'c7', 'linked': 2, 'url': 'http://127.0.0.1:3000/user/', 'fetched': true, 'code': 200, 'len': 206, 'decl_mime': 'text/html', 'sniff_mime': 'text/html', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x6b5ffc86 }
];
